# Generated by Django 3.1.3 on 2020-11-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Major',
            new_name='Department',
        ),
    ]
