# Generated by Django 3.1.3 on 2020-11-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20201113_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='university',
            new_name='faculty',
        ),
    ]
