# Generated by Django 3.1.3 on 2020-11-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_auto_20201113_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='departmentType',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='educaitonLanguage',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='minimumPuan',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='minimumRanking',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='presentageofScholarhip',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='puanType',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='theTimeofEducation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='tution',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='years',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='cover_photo_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='images',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='numberOfAcademicians',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='numberOfForeignStudents',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='numberOfLocalStudents',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='profile_photo_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='universityType',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='info',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Privaligities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university')),
            ],
        ),
        migrations.CreateModel(
            name='Campuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university')),
            ],
        ),
    ]
