# Generated by Django 3.1.3 on 2020-11-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_auto_20201118_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='website',
            new_name='website_link',
        ),
        migrations.AddField(
            model_name='university',
            name='facebook_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='instagram_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='linkedin_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='pinterest_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='twitter_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
