# Generated by Django 3.1.3 on 2020-11-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_auto_20201118_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='facebook_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='images',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='instagram_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='linkedin_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='pinterest_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='twitter_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
