# Generated by Django 3.1.3 on 2020-11-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_auto_20201118_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='profile_photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
