# Generated by Django 3.1.3 on 2020-11-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_auto_20201120_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='images',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
