# Generated by Django 3.1.3 on 2020-12-01 05:28

import Apps.universities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0011_remove_university_detailedinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='cover_photo',
            field=models.ImageField(blank=True, default='images/default/cover.jpg', null=True, upload_to=Apps.universities.models.University.upload_to_func),
        ),
        migrations.AlterField(
            model_name='university',
            name='profile_photo',
            field=models.ImageField(blank=True, default='images/default/logo.jpg', null=True, upload_to=Apps.universities.models.University.upload_to_func),
        ),
    ]
