# Generated by Django 3.1.3 on 2020-12-01 11:01

import Apps.universities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0012_auto_20201201_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='detailedInfo',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='university',
            name='profile_photo',
            field=models.ImageField(blank=True, default='images/default/logo.png', null=True, upload_to=Apps.universities.models.University.upload_to_func),
        ),
    ]
