# Generated by Django 3.1.3 on 2020-12-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0013_auto_20201201_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='detailedInfo',
            field=models.TextField(default='', max_length=800),
        ),
    ]
