# Generated by Django 3.1.3 on 2020-12-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0014_auto_20201201_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'faculties'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'universities'},
        ),
        migrations.AlterField(
            model_name='university',
            name='detailedInfo',
            field=models.TextField(default='', max_length=3200),
        ),
    ]
