# Generated by Django 3.1.3 on 2020-12-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0015_auto_20201201_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentType',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='educaitonLanguage',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='minimumPuan',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='minimumRanking',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='presentageofScholarhip',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='puanType',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='theTimeofEducation',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='tution',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='years',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='facebook_link',
            field=models.CharField(blank=True, default='https://www.facebook.com/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='instagram_link',
            field=models.CharField(blank=True, default='https://www.instagram.com/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='linkedin_link',
            field=models.CharField(blank=True, default='https://www.linkedin.com/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='pinterest_link',
            field=models.CharField(blank=True, default='https://tr.pinterest.com/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='twitter_link',
            field=models.CharField(blank=True, default='https://twitter.com/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='website_link',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
