# Generated by Django 3.1.3 on 2020-12-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0016_auto_20201202_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'faculties',
            },
        ),
        migrations.RemoveField(
            model_name='department',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='university',
        ),
        migrations.RemoveField(
            model_name='privaligities',
            name='university',
        ),
        migrations.DeleteModel(
            name='Campuses',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Privaligities',
        ),
        migrations.AddField(
            model_name='university',
            name='facultyList',
            field=models.ManyToManyField(blank=True, to='universities.Faculties'),
        ),
    ]
