# Generated by Django 3.1.3 on 2020-12-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0017_auto_20201202_2052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculties',
            new_name='Faculty',
        ),
    ]
