# Generated by Django 3.1.3 on 2020-12-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0018_auto_20201202_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'campuses',
            },
        ),
        migrations.CreateModel(
            name='Privilige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'priviligies',
            },
        ),
        migrations.AddField(
            model_name='university',
            name='campusList',
            field=models.ManyToManyField(blank=True, to='universities.Campus'),
        ),
        migrations.AddField(
            model_name='university',
            name='priviligeList',
            field=models.ManyToManyField(blank=True, to='universities.Privilige'),
        ),
    ]
