# Generated by Django 3.1.3 on 2020-12-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0019_auto_20201202_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('departmentType', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('puanType', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('minimumPuan', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('minimumRanking', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('educaitonLanguage', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('theTimeofEducation', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('presentageofScholarhip', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('tution', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('years', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='departmentList',
            field=models.ManyToManyField(blank=True, to='universities.Department'),
        ),
    ]
