# Generated by Django 3.1.3 on 2020-12-03 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appmakales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makale',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='makale',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makale',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
