# Generated by Django 3.1.3 on 2020-12-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmakales', '0002_auto_20201203_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makale',
            name='date',
        ),
    ]
