# Generated by Django 3.1.2 on 2020-11-01 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manager2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='manager',
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager',
            field=models.ManyToManyField(null=True, related_name='_customuser_manager_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
