# Generated by Django 3.1.2 on 2020-11-01 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_manager3'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manager4',
            field=models.ManyToManyField(null=True, related_name='_customuser_manager4_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
