# Generated by Django 3.1.2 on 2020-11-01 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_manager4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='manager4',
            field=models.ManyToManyField(related_name='_customuser_manager4_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
