# Generated by Django 3.1.2 on 2020-11-01 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201101_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='manager4',
            field=models.ManyToManyField(related_name='employee4', to=settings.AUTH_USER_MODEL),
        ),
    ]
