# Generated by Django 3.1.2 on 2020-11-01 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201101_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='manager4',
        ),
        migrations.AddField(
            model_name='customuser',
            name='followersRec',
            field=models.ManyToManyField(related_name='followingRes', to=settings.AUTH_USER_MODEL),
        ),
    ]
