# Generated by Django 3.1.3 on 2020-11-03 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201102_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followersRec',
        ),
        migrations.AddField(
            model_name='customuser',
            name='followingList',
            field=models.ManyToManyField(related_name='followerList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
