# Generated by Django 3.1.3 on 2020-11-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
