# Generated by Django 3.1.3 on 2020-12-01 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_subscribers_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AddField(
            model_name='subscribers',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 11, 11, 57, 719177, tzinfo=utc), verbose_name='Subscription date'),
        ),
    ]
