# Generated by Django 3.1.3 on 2020-12-04 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20201201_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='createdTime',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 12, 4)),
        ),
    ]
