# Generated by Django 3.1.3 on 2020-12-04 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20201204_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='createdTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
