# Generated by Django 3.1.3 on 2020-12-04 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0020_auto_20201202_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, max_length=200)),
                ('startDate', models.DateTimeField(blank=True, verbose_name='date started')),
                ('endDate', models.DateTimeField(blank=True, verbose_name='date ended')),
                ('university', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='universities.university')),
            ],
        ),
    ]
