# Generated by Django 3.1.3 on 2020-12-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='text',
            new_name='name',
        ),
    ]
