# Generated by Django 3.1.3 on 2020-12-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20201204_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date started'),
        ),
    ]
