# Generated by Django 3.1.3 on 2020-12-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0020_auto_20201202_2107'),
        ('calendars', '0003_auto_20201204_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='university',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventList', to='universities.university'),
        ),
    ]
